### ISSUE TITLE
Portal 2 UI todo

### ISSUE THREAD

**Issue by vrad-exe** [vrad-exe/P2ASW#1]
- [x] `#L4D360UI_BACK` is missing, I don't know why
- [x] Missing cvars for some settings causing them to not work and/or produce console spam. Need to port the relevant cvars if they're in game code, or remove the settings if not.
- [x] ~All the challenge mode stuff is disabled because it relies on leaderboard related code that we don't have. That will need to be RE'd first.~ Not fixing for this PR
- [x] I hooked chapter unlocking up to `sv_unlockedchapters` instead of title data, which is probably better for mods anyway, but technically inaccurate. I also haven't added any code to handle actually unlocking chapters yet, so you have to change it manually
- [x] Saves are searched in the wrong place (Swarm doesn't use the steam id subfolders)
- [x] Save thumbnails look messed up (which is still better than Portal 2 not having them at all)
	- The problem is with taking the screenshots, it includes the gameui blur background
- [x] The tileflip animations are totally messed up. Now fixed, however:	
	- [ ] It re-animates every time the console is closed
	- [ ] On some screens the tiles flip out of order
	- [x] It locks the mouse, because of a function Swarm is missing. Not sure how to work around this.
	- [ ] Sometimes the tile flip is delayed until after the next dialog is already showing, causing a buggy appearance
		- Fairly consistently happens for the first tileflip in the session (usually the intro screen, unless the console is open) and generic confirmations (like quit game)
- [x] Controller settings shows a steam controller graphic layered on top of the xbox controller
- [x] There's a ton of console spam from the `$GAMECONSOLE`, `$DECK` etc. tags not being recognized.
- Missing features from recent Portal 2 updates:
	- [x] Better video settings descriptions
	- [x] Local Splitscreen button in the co-op mode dialog
	- [x] Footer never shows controller button prompts - apparently they were behind a console ifdef until some update
	- [x] Snap cursor to bottom right corner of screen when using a controller
- [x] Loading screens aren't detecting widescreen properly
- [x] Missing coop avatars
- [x] Can't start any games through the UI, it black screens
- [x] Footer buttons aren't all caps anymore. They were earlier. Now they are again. ???????
- [x] I want to see if I can fix the controller binding stuff easily
- [x] Figure out the scoreboard crash
